Repository SCKorea/sc-backend, pull requests merged in 2024-01, with the labels that each got.

#68 feat: 뉴스 컨텐츠 수정 기능 추가 (#64)
  src/docs/asciidoc/news-api.adoc
  src/main/kotlin/kr/galaxyhub/sc/api/v1/news/NewsControllerV1.kt
  src/main/kotlin/kr/galaxyhub/sc/api/v1/news/dto/NewsUpdateRequest.kt
  src/main/kotlin/kr/galaxyhub/sc/news/application/NewsCommandService.kt
  src/main/kotlin/kr/galaxyhub/sc/news/application/NewsQueryService.kt
  src/main/kotlin/kr/galaxyhub/sc/news/domain/Content.kt
  src/main/kotlin/kr/galaxyhub/sc/news/domain/NewsRepository.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslationCommandService.kt
  src/test/kotlin/kr/galaxyhub/sc/api/v1/news/NewsControllerV1Test.kt
  src/test/kotlin/kr/galaxyhub/sc/news/application/NewsCommandServiceTest.kt
Labels: 뉴스

#71 refactor: build.gradle.kts 정리 (#65)
  build.gradle.kts
Labels: 🏢 인프라, 🛠 수정

#70 feat: MockWebServer 일부 테스트 코드 개선 (#69)
  src/test/kotlin/kr/galaxyhub/sc/auth/infra/DiscordOAuth2ClientTest.kt
  src/test/kotlin/kr/galaxyhub/sc/common/support/MockWebServerDsl.kt
  src/test/kotlin/kr/galaxyhub/sc/translation/infra/DeepLTranslatorClientTest.kt
Labels: 🧪 테스트, ⚙️ 리팩터링

#73 feat: 테스트 컨테이너 docker-compose 설정 추가
  build.gradle.kts
  src/test/kotlin/kr/galaxyhub/sc/GalaxyhubApplicationTests.kt
  src/test/kotlin/kr/galaxyhub/sc/config/spec/IntegrationSpec.kt
  src/test/resources/application-test.yml
  src/test/resources/docker-compose.yml
Labels: 🏢 인프라, 🧪 테스트, 🙋‍♀️ 제안

#75 feat: Github Action CI 스크립트 대상 브랜치 확장 (#74)
  .github/workflows/cd-back-dev.yml
  .github/workflows/ci-back.yml
Labels: 🏢 인프라

#72 feat: testcontainers 추가 (#16)
  build.gradle.kts
  src/test/kotlin/kr/galaxyhub/sc/GalaxyhubApplicationTests.kt
  src/test/kotlin/kr/galaxyhub/sc/config/spec/IntegrationSpec.kt
  src/test/resources/application-test.yml
  src/test/resources/docker-compose.yml
Labels: 🏢 인프라, 🧪 테스트

#77 refactor: TranslationCommandService translate 메서드 개선 (#76)
  src/main/kotlin/kr/galaxyhub/sc/api/v1/translation/dto/TranslationRequest.kt
  src/main/kotlin/kr/galaxyhub/sc/common/config/AsyncConfig.kt
  src/main/kotlin/kr/galaxyhub/sc/news/application/NewsAppendContentEventListener.kt
  src/main/kotlin/kr/galaxyhub/sc/news/application/NewsCommandService.kt
  src/main/kotlin/kr/galaxyhub/sc/news/application/dto/NewsAppendContentEvent.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslateProgressionStatusChangeService.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslateResultEventListener.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslationAppendContentEventListener.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslationCommandService.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslationQueryService.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslatorClient.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/TranslatorClients.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/dto/TranslationCommand.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/application/dto/TranslatorFailureEvent.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/config/TranslatorClientConfig.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/domain/TranslateProgressionRepository.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/domain/TranslatorClient.kt
  src/main/kotlin/kr/galaxyhub/sc/translation/infra/DeepLTranslatorClient.kt
  src/test/kotlin/kr/galaxyhub/sc/news/application/NewsCommandServiceTest.kt
  src/test/kotlin/kr/galaxyhub/sc/news/fixture/TranslateProgressionFixture.kt
  src/test/kotlin/kr/galaxyhub/sc/translation/application/TranslationCommandServiceTest.kt
  src/test/kotlin/kr/galaxyhub/sc/translation/application/TranslationProgressionStatusChangeServiceTest.kt
  src/test/kotlin/kr/galaxyhub/sc/translation/domain/MemoryTranslateProgressionRepository.kt
  src/test/kotlin/kr/galaxyhub/sc/translation/infra/DeepLTranslatorClientTest.kt
Labels: ⚙️ 리팩터링, 번역

#83 fix: Testcontainers 사용 시 버그 수정 (#82)
  build.gradle.kts
  src/test/kotlin/kr/galaxyhub/sc/config/EnableTestcontianers.kt
  src/test/kotlin/kr/galaxyhub/sc/config/KotestProjectConfig.kt
  src/test/kotlin/kr/galaxyhub/sc/config/TestContainerExtension.kt
  src/test/kotlin/kr/galaxyhub/sc/config/spec/ControllerTestSpec.kt
  src/test/kotlin/kr/galaxyhub/sc/config/spec/IntegrationSpec.kt
  src/test/resources/docker-compose.yml
Labels: 🧪 테스트, 🛠 수정
